# Probability
## Introduction to Probabilities
In 1814, Pierre-Simon Laplace wrote:  
> Probability theory is nothing but common sense reduced to calculation. 
... [Probability] is thus simply a fraction whose numerator is the 
number of favorable cases and whose denominator is the number of all 
the cases possible ... when nothing leads us to expect that any one of 
these cases should occur more than any other.
Laplace nailed it. To untangle a probability problem, all you have to do 
is define exactly what the cases are, and careful count the favorable 
and total cases. Let's be clear on our vocabulary words:
- **Trial**
A single occurrence with an outcome that is uncertain until we observe it.  
*For example, rolling a single die.*
- **Outcome**
A possible result of a trial; one particular state of the world. What 
Laplace calls a **case.** *For example:* `4`.
- **Sample Space**
The set of all possible outcomes for the trial.   
*For example,* `{1, 2, 3, 4, 5, 6}`.
- **Event**
A subset of the sample space, a set of outcomes that together have some 
property we are interested in.  
*For example, the event "even die roll" is the set of outcomes* 
`{2, 4, 6}`.
- **Probability**
As Laplace said, the probability of an event with respect to a sample 
space is the "number of favorable cases" (outcomes from the sample space 
that are in the event) divided by the "number of all the cases" in the 
sample space (assuming "nothing leads us to expect that any one of these 
cases should occur more than any other"). Since this is a proper 
fraction, probability will always be a number between 0 (representing an 
impossible event) and 1 (representing a certain event).  
*For example, the probability of an even die roll is 3/6 = 1/2.*

In [4]:
import random #generador de numeros aleatorios
import numpy as np
import pandas as pd
import matplotlib.pyplot as plot

In [5]:
# 1. generacion de lanzamientos de una moneda, sello = 0, cara = 1
toss = random.randint(0,1)
print(toss)

1


In [6]:
# generación de lanzamiento de monedas, con una estructura de control (for) las secuencias de control son for, if, while.
toss_results = []
for i in range(10):
    result = random.randint(0,1)
    toss_results.append(result)
print(toss_results)

[1, 1, 0, 1, 1, 1, 1, 1, 1, 0]


In [7]:
# generación de lanzamiento de monedas controlado
random.seed(2024)
toss_results = []
for i in range(10):
    result = random.randint(0,1)
    toss_results.append(result)
print(toss_results)

[1, 0, 1, 0, 1, 1, 0, 1, 1, 1]


In [8]:
# calcular la probabilidad de que salga cara en 10 lanzamientos de moneda
toss_results = []
for i in range(1000000):
    result = random.randint(0,1)
    toss_results.append(result)
#print(toss_results)
sum(toss_results)/len(toss_results)

0.499507

In [9]:
from fractions import Fraction

In [10]:
Fraction(1,3)#representacion de una fraccion en python

Fraction(1, 3)

In [11]:
# 2. Calcular la probabilidad de sacar par en un lanzamiento de dados
even = {2,4,6}
points = {1,2,3,4,5,6} #asumimos que el dado esta perfectamente balanceado
set.intersection(even,points)

{2, 4, 6}

In [12]:
def Pr(event,space):
    return Fraction(len(set.intersection(event,space)), len(space))

In [13]:
Pr(even,points)

Fraction(1, 2)

In [14]:
# calcular la probabilidad de obtener 5 o 6 en un lanzamiento de dados
success = {5,6}
points = {1,2,3,4,5,6}
Pr(success,points)

Fraction(1, 3)

In [15]:
# This refers to a discrete sample space, so the probability is related to a discrete event

In [16]:
# box 1 = [1,0,0,0] probabilidad de exito es de 1/4 = 0.25
# box 2 = [1,1,0,0,0] probabilidad de exito es de 2/5 = 0.4
# Cual caja escogio Ali? la caja 2

In [17]:
box1 = np.array([1,0,0,0]) #este es un vector ([])
np.random.choice(box1,1) #simula el evento de sacar una piedra

array([0])

In [18]:
trial = np.random.choice(box1, 100000)
trial.mean()

np.float64(0.2503)

In [19]:
box2 = np.array([1,0,1,0,0])
trial = np.random.choice(box2,10000)
trial.mean()#aqui funciona mean porque solo hay dos resultados 0 y 1 y ademas el resultado exitoso es 1

np.float64(0.3904)

In [20]:
# cuando son mas de dos resultados se usa
success = np.isin(trial,[1])
probability = len(trial[success])/len(trial)
probability

0.3904

In [21]:
np.random.seed(2024)
yankenpo = np.array([1,2,3])
trial = np.random.choice(yankenpo,10)
success = np.isin(trial,[2]) # isin nos retorna un vector de booleanos
probability = len(trial[success])/len(trial)
probability

0.2

In [22]:
yankenpo

array([1, 2, 3])

In [23]:
trial

array([1, 3, 1, 1, 1, 3, 2, 2, 1, 3])

In [24]:
success

array([False, False, False, False, False, False,  True,  True, False,
       False])

In [25]:
trial[success] #es un filtro para retornar los valores true

array([2, 2])

In [26]:
results =  np.array([14,22,21,15,18,23,19])
success = np.isin(results,[21])
results[success]

array([21])

In [27]:
# 3. El siguiente problema muestra la probabilidad condicional
# cual es la probabilidad de sacar un As en una segunda extraccion si en la primera ya saque un As
# cuantos Ases hay en una baraja? 4
# cuantos nipes hay en una baraja? 52
# cual es la probabilidad de sacar un As en la primera extraccion, 4/52 = 1/13
# si ya saque un As de la baraja cuantos nipes quedan? 51 y 3 Ases
# en una segunda extraccion la probabilidad de sacar un As es: Pr(sacar As en segunda extraccion|sacar As en primera extraccion)
# por lo tanto es una probabilidad condicionada al evento de haber sacado un As en la primera extraccion 
# la formula es Pr = 3/51
# Pr(A and B) =  Pr(A) * Pr(B|A)
# si A y B son idendependientes entonces Pr(A|B)=Pr(A)
# Pr( A and B and C) = Pr(A)*Pr(B|A)*Pr(C|A and B)*Regla de la cadena
# Pr (A or B) = Pr(A) + Pr(B) - Pr(A and B)

In [28]:
# en un avion  hay 3 bombas, cada bomba  tiene 0.4 probabilidades de explotar, cual es la probabilidad de que la segunda bomba explote
# cual es la probabilidad que las 3 bombas exploten a la vez
0.4*0.4*0.4

0.06400000000000002

In [33]:
# cual es la probabilidad de que en una sala con 10 personas, dos cumplan años el mismo dia. Y en una sala con 20 personas, 
# con 30 personas, y en una con 50?
def same_birthday(n):
    days =  np.arange(1,366) # hago la lista
    bday = np.random.choice(days,n) # escojo al azar 'n'
    return np.any(np.bincount(bday)>1) # .any me dice si alguno es mayor que 1 

In [38]:
same_birthday(10)

np.True_

In [41]:
counter = 0
for i in range(10000):
    if same_birthday(30):
        counter += 1
counter/10000

0.708

In [42]:
counter = 0
for i in range(10000):
    if same_birthday(50):
        counter += 1
counter/10000

0.969